apiVersion: v1
kind: Service
metadata:
  name: watchmen
  namespace: watchmen
  labels:
    app.kubernetes.io/name: watchmen
spec:
  type: ClusterIP
  selector:
    app: watchmen
  ports:
    - name: http
      port: 80
      targetPort: http   # references the named port on the container (3000)
      protocol: TCP
